Dockerfile cleanup

diff --git a/nextcloud/Dockerfile b/nextcloud/Dockerfile
--- a/nextcloud/Dockerfile
+++ b/nextcloud/Dockerfile
@@ -65,26 +65,22 @@ RUN set -ex; \
     ldconfig /usr/local/lib; \
     cd ..
 
+# Nextcloud dependencies
+RUN set -ex; \
+    apt-get install -y --no-install-recommends \
+#	libmagickcore-6.q16-6-extra \
+	libbz2-dev \
+	ffmpeg \
+	intel-media-va-driver
+
+RUN set -ex; \
+    docker-php-ext-install bz2
+
+# Cleanup
 RUN rm -rf libde265; \
     rm -rf libheif; \
     rm -rf ImageMagick
 
-# Nextcloud dependencies
-RUN set -ex; \
-    \
-    apt-get install -y --no-install-recommends \
-	libbz2-dev \
-	ffmpeg \
-	intel-media-va-driver \
-#	libmagickcore-6.q16-6-extra \
-    ; \
-    rm -rf /var/lib/apt/lists/*
-
-RUN set -ex; \
-    \
-    docker-php-ext-install bz2
-
-# Cleanup
 RUN apt-get remove -y libtool automake autoconf pkgconf cmake build-essential git; \
-	apt-get autoremove -y
-
+	apt-get autoremove -y; \
+    rm -rf /var/lib/apt/lists/*
